[package]
name = "cake-web-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
exclude.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true