// @generated automatically by Diesel CLI.

pub mod cake_web {
    /// A module containing custom SQL type definitions
    ///
    /// (Automatically generated by Diesel.)
    pub mod sql_types {
        /// The `cake_web.user_role` SQL type
        ///
        /// (Automatically generated by Diesel.)
        #[derive(diesel::query_builder::QueryId, diesel::sql_types::SqlType)]
        #[diesel(postgres_type(name = "user_role", schema = "cake_web"))]
        pub struct UserRole;
    }

    diesel::table! {
        use diesel::sql_types::*;
        use super::sql_types::UserRole;

        /// Representation of the `cake_web.users` table.
        ///
        /// (Automatically generated by Diesel.)
        cake_web.users (id) {
            /// The `id` column of the `cake_web.users` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int4,
            /// The `username` column of the `cake_web.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 20]
            username -> Varchar,
            /// The `password` column of the `cake_web.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 50]
            password -> Varchar,
            /// The `email` column of the `cake_web.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            email -> Varchar,
            /// The `user_role` column of the `cake_web.users` table.
            ///
            /// Its SQL type is `UserRole`.
            ///
            /// (Automatically generated by Diesel.)
            user_role -> UserRole,
            /// The `is_active` column of the `cake_web.users` table.
            ///
            /// Its SQL type is `Bool`.
            ///
            /// (Automatically generated by Diesel.)
            is_active -> Bool,
            /// The `updated_at` column of the `cake_web.users` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Timestamptz,
            /// The `created_at` column of the `cake_web.users` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Timestamptz,
        }
    }
}
