[package]
name = "cake-web-dto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
exclude.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
utoipa.workspace = true