export const MODAL_BODY_TYPES = {
  USER_DETAIL: "USER_DETAIL",
  LEAD_ADD_NEW: "LEAD_ADD_NEW",
  CONFIRMATION: "CONFIRMATION",
  DEFAULT: "",
};

export const RIGHT_DRAWER_TYPES = {
  NOTIFICATION: "NOTIFICATION", DEFAULT: "DEFAULT"

};

export const CONFIRMATION_MODAL_CLOSE_TYPES = {
  LEAD_DELETE: "LEAD_DELETE",
};
